# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nora/Documents/ing1/projets/42sh

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nora/Documents/ing1/projets/42sh

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nora/Documents/ing1/projets/42sh/CMakeFiles /home/nora/Documents/ing1/projets/42sh/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nora/Documents/ing1/projets/42sh/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests_parser

# Build rule for target.
tests_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests_parser
.PHONY : tests_parser

# fast build rule for target.
tests_parser/fast:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/build
.PHONY : tests_parser/fast

#=============================================================================
# Target rules for targets named 42sh

# Build rule for target.
42sh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 42sh
.PHONY : 42sh

# fast build rule for target.
42sh/fast:
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/build
.PHONY : 42sh/fast

#=============================================================================
# Target rules for targets named tests_storage

# Build rule for target.
tests_storage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests_storage
.PHONY : tests_storage

# fast build rule for target.
tests_storage/fast:
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/build
.PHONY : tests_storage/fast

#=============================================================================
# Target rules for targets named tests_lexer

# Build rule for target.
tests_lexer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests_lexer
.PHONY : tests_lexer

# fast build rule for target.
tests_lexer/fast:
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/build
.PHONY : tests_lexer/fast

#=============================================================================
# Target rules for targets named ast_print

# Build rule for target.
ast_print: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ast_print
.PHONY : ast_print

# fast build rule for target.
ast_print/fast:
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/build
.PHONY : ast_print/fast

#=============================================================================
# Target rules for targets named token_printer

# Build rule for target.
token_printer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 token_printer
.PHONY : token_printer

# fast build rule for target.
token_printer/fast:
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/build
.PHONY : token_printer/fast

src/ast/ast.o: src/ast/ast.c.o

.PHONY : src/ast/ast.o

# target to build an object file
src/ast/ast.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/ast/ast.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/ast/ast.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/ast/ast.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/ast/ast.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/ast/ast.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/ast/ast.c.o
.PHONY : src/ast/ast.c.o

src/ast/ast.i: src/ast/ast.c.i

.PHONY : src/ast/ast.i

# target to preprocess a source file
src/ast/ast.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/ast/ast.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/ast/ast.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/ast/ast.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/ast/ast.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/ast/ast.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/ast/ast.c.i
.PHONY : src/ast/ast.c.i

src/ast/ast.s: src/ast/ast.c.s

.PHONY : src/ast/ast.s

# target to generate assembly for a file
src/ast/ast.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/ast/ast.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/ast/ast.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/ast/ast.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/ast/ast.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/ast/ast.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/ast/ast.c.s
.PHONY : src/ast/ast.c.s

src/ast/free.o: src/ast/free.c.o

.PHONY : src/ast/free.o

# target to build an object file
src/ast/free.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/ast/free.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/ast/free.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/ast/free.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/ast/free.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/ast/free.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/ast/free.c.o
.PHONY : src/ast/free.c.o

src/ast/free.i: src/ast/free.c.i

.PHONY : src/ast/free.i

# target to preprocess a source file
src/ast/free.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/ast/free.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/ast/free.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/ast/free.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/ast/free.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/ast/free.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/ast/free.c.i
.PHONY : src/ast/free.c.i

src/ast/free.s: src/ast/free.c.s

.PHONY : src/ast/free.s

# target to generate assembly for a file
src/ast/free.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/ast/free.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/ast/free.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/ast/free.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/ast/free.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/ast/free.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/ast/free.c.s
.PHONY : src/ast/free.c.s

src/eval/ast_print.o: src/eval/ast_print.c.o

.PHONY : src/eval/ast_print.o

# target to build an object file
src/eval/ast_print.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/eval/ast_print.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/eval/ast_print.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/eval/ast_print.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/eval/ast_print.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/eval/ast_print.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/eval/ast_print.c.o
.PHONY : src/eval/ast_print.c.o

src/eval/ast_print.i: src/eval/ast_print.c.i

.PHONY : src/eval/ast_print.i

# target to preprocess a source file
src/eval/ast_print.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/eval/ast_print.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/eval/ast_print.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/eval/ast_print.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/eval/ast_print.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/eval/ast_print.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/eval/ast_print.c.i
.PHONY : src/eval/ast_print.c.i

src/eval/ast_print.s: src/eval/ast_print.c.s

.PHONY : src/eval/ast_print.s

# target to generate assembly for a file
src/eval/ast_print.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/eval/ast_print.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/eval/ast_print.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/eval/ast_print.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/eval/ast_print.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/eval/ast_print.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/eval/ast_print.c.s
.PHONY : src/eval/ast_print.c.s

src/eval/token_printer.o: src/eval/token_printer.c.o

.PHONY : src/eval/token_printer.o

# target to build an object file
src/eval/token_printer.c.o:
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/eval/token_printer.c.o
.PHONY : src/eval/token_printer.c.o

src/eval/token_printer.i: src/eval/token_printer.c.i

.PHONY : src/eval/token_printer.i

# target to preprocess a source file
src/eval/token_printer.c.i:
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/eval/token_printer.c.i
.PHONY : src/eval/token_printer.c.i

src/eval/token_printer.s: src/eval/token_printer.c.s

.PHONY : src/eval/token_printer.s

# target to generate assembly for a file
src/eval/token_printer.c.s:
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/eval/token_printer.c.s
.PHONY : src/eval/token_printer.c.s

src/exec/commands.o: src/exec/commands.c.o

.PHONY : src/exec/commands.o

# target to build an object file
src/exec/commands.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/exec/commands.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/exec/commands.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/exec/commands.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/exec/commands.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/exec/commands.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/exec/commands.c.o
.PHONY : src/exec/commands.c.o

src/exec/commands.i: src/exec/commands.c.i

.PHONY : src/exec/commands.i

# target to preprocess a source file
src/exec/commands.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/exec/commands.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/exec/commands.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/exec/commands.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/exec/commands.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/exec/commands.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/exec/commands.c.i
.PHONY : src/exec/commands.c.i

src/exec/commands.s: src/exec/commands.c.s

.PHONY : src/exec/commands.s

# target to generate assembly for a file
src/exec/commands.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/exec/commands.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/exec/commands.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/exec/commands.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/exec/commands.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/exec/commands.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/exec/commands.c.s
.PHONY : src/exec/commands.c.s

src/exec/exec.o: src/exec/exec.c.o

.PHONY : src/exec/exec.o

# target to build an object file
src/exec/exec.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/exec/exec.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/exec/exec.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/exec/exec.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/exec/exec.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/exec/exec.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/exec/exec.c.o
.PHONY : src/exec/exec.c.o

src/exec/exec.i: src/exec/exec.c.i

.PHONY : src/exec/exec.i

# target to preprocess a source file
src/exec/exec.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/exec/exec.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/exec/exec.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/exec/exec.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/exec/exec.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/exec/exec.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/exec/exec.c.i
.PHONY : src/exec/exec.c.i

src/exec/exec.s: src/exec/exec.c.s

.PHONY : src/exec/exec.s

# target to generate assembly for a file
src/exec/exec.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/exec/exec.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/exec/exec.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/exec/exec.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/exec/exec.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/exec/exec.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/exec/exec.c.s
.PHONY : src/exec/exec.c.s

src/expansion/var_expansion.o: src/expansion/var_expansion.c.o

.PHONY : src/expansion/var_expansion.o

# target to build an object file
src/expansion/var_expansion.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/expansion/var_expansion.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/expansion/var_expansion.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/expansion/var_expansion.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/expansion/var_expansion.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/expansion/var_expansion.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/expansion/var_expansion.c.o
.PHONY : src/expansion/var_expansion.c.o

src/expansion/var_expansion.i: src/expansion/var_expansion.c.i

.PHONY : src/expansion/var_expansion.i

# target to preprocess a source file
src/expansion/var_expansion.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/expansion/var_expansion.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/expansion/var_expansion.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/expansion/var_expansion.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/expansion/var_expansion.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/expansion/var_expansion.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/expansion/var_expansion.c.i
.PHONY : src/expansion/var_expansion.c.i

src/expansion/var_expansion.s: src/expansion/var_expansion.c.s

.PHONY : src/expansion/var_expansion.s

# target to generate assembly for a file
src/expansion/var_expansion.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/expansion/var_expansion.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/expansion/var_expansion.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/expansion/var_expansion.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/expansion/var_expansion.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/expansion/var_expansion.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/expansion/var_expansion.c.s
.PHONY : src/expansion/var_expansion.c.s

src/lexer/lex_evaluation.o: src/lexer/lex_evaluation.c.o

.PHONY : src/lexer/lex_evaluation.o

# target to build an object file
src/lexer/lex_evaluation.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/lexer/lex_evaluation.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lex_evaluation.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/lexer/lex_evaluation.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/lexer/lex_evaluation.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/lexer/lex_evaluation.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/lexer/lex_evaluation.c.o
.PHONY : src/lexer/lex_evaluation.c.o

src/lexer/lex_evaluation.i: src/lexer/lex_evaluation.c.i

.PHONY : src/lexer/lex_evaluation.i

# target to preprocess a source file
src/lexer/lex_evaluation.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/lexer/lex_evaluation.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lex_evaluation.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/lexer/lex_evaluation.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/lexer/lex_evaluation.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/lexer/lex_evaluation.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/lexer/lex_evaluation.c.i
.PHONY : src/lexer/lex_evaluation.c.i

src/lexer/lex_evaluation.s: src/lexer/lex_evaluation.c.s

.PHONY : src/lexer/lex_evaluation.s

# target to generate assembly for a file
src/lexer/lex_evaluation.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/lexer/lex_evaluation.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lex_evaluation.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/lexer/lex_evaluation.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/lexer/lex_evaluation.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/lexer/lex_evaluation.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/lexer/lex_evaluation.c.s
.PHONY : src/lexer/lex_evaluation.c.s

src/lexer/lexer.o: src/lexer/lexer.c.o

.PHONY : src/lexer/lexer.o

# target to build an object file
src/lexer/lexer.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/lexer/lexer.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/lexer/lexer.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/lexer/lexer.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/lexer/lexer.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/lexer/lexer.c.o
.PHONY : src/lexer/lexer.c.o

src/lexer/lexer.i: src/lexer/lexer.c.i

.PHONY : src/lexer/lexer.i

# target to preprocess a source file
src/lexer/lexer.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/lexer/lexer.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/lexer/lexer.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/lexer/lexer.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/lexer/lexer.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/lexer/lexer.c.i
.PHONY : src/lexer/lexer.c.i

src/lexer/lexer.s: src/lexer/lexer.c.s

.PHONY : src/lexer/lexer.s

# target to generate assembly for a file
src/lexer/lexer.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/lexer/lexer.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/lexer/lexer.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/lexer/lexer.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/lexer/lexer.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/lexer/lexer.c.s
.PHONY : src/lexer/lexer.c.s

src/lexer/token.o: src/lexer/token.c.o

.PHONY : src/lexer/token.o

# target to build an object file
src/lexer/token.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/lexer/token.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/lexer/token.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/lexer/token.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/lexer/token.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/lexer/token.c.o
.PHONY : src/lexer/token.c.o

src/lexer/token.i: src/lexer/token.c.i

.PHONY : src/lexer/token.i

# target to preprocess a source file
src/lexer/token.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/lexer/token.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/lexer/token.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/lexer/token.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/lexer/token.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/lexer/token.c.i
.PHONY : src/lexer/token.c.i

src/lexer/token.s: src/lexer/token.c.s

.PHONY : src/lexer/token.s

# target to generate assembly for a file
src/lexer/token.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/lexer/token.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/lexer/token.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/lexer/token.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/lexer/token.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/lexer/token.c.s
.PHONY : src/lexer/token.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/main.c.s
.PHONY : src/main.c.s

src/parser/parser.o: src/parser/parser.c.o

.PHONY : src/parser/parser.o

# target to build an object file
src/parser/parser.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/parser/parser.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/parser.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/parser/parser.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/parser/parser.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/parser/parser.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/parser/parser.c.o
.PHONY : src/parser/parser.c.o

src/parser/parser.i: src/parser/parser.c.i

.PHONY : src/parser/parser.i

# target to preprocess a source file
src/parser/parser.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/parser/parser.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/parser.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/parser/parser.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/parser/parser.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/parser/parser.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/parser/parser.c.i
.PHONY : src/parser/parser.c.i

src/parser/parser.s: src/parser/parser.c.s

.PHONY : src/parser/parser.s

# target to generate assembly for a file
src/parser/parser.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/parser/parser.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/parser/parser.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/parser/parser.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/parser/parser.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/parser/parser.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/parser/parser.c.s
.PHONY : src/parser/parser.c.s

src/print/ast_print_dot.o: src/print/ast_print_dot.c.o

.PHONY : src/print/ast_print_dot.o

# target to build an object file
src/print/ast_print_dot.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/print/ast_print_dot.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/print/ast_print_dot.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/print/ast_print_dot.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/print/ast_print_dot.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/print/ast_print_dot.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/print/ast_print_dot.c.o
.PHONY : src/print/ast_print_dot.c.o

src/print/ast_print_dot.i: src/print/ast_print_dot.c.i

.PHONY : src/print/ast_print_dot.i

# target to preprocess a source file
src/print/ast_print_dot.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/print/ast_print_dot.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/print/ast_print_dot.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/print/ast_print_dot.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/print/ast_print_dot.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/print/ast_print_dot.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/print/ast_print_dot.c.i
.PHONY : src/print/ast_print_dot.c.i

src/print/ast_print_dot.s: src/print/ast_print_dot.c.s

.PHONY : src/print/ast_print_dot.s

# target to generate assembly for a file
src/print/ast_print_dot.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/print/ast_print_dot.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/print/ast_print_dot.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/print/ast_print_dot.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/print/ast_print_dot.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/print/ast_print_dot.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/print/ast_print_dot.c.s
.PHONY : src/print/ast_print_dot.c.s

src/print/ast_print_main.o: src/print/ast_print_main.c.o

.PHONY : src/print/ast_print_main.o

# target to build an object file
src/print/ast_print_main.c.o:
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/print/ast_print_main.c.o
.PHONY : src/print/ast_print_main.c.o

src/print/ast_print_main.i: src/print/ast_print_main.c.i

.PHONY : src/print/ast_print_main.i

# target to preprocess a source file
src/print/ast_print_main.c.i:
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/print/ast_print_main.c.i
.PHONY : src/print/ast_print_main.c.i

src/print/ast_print_main.s: src/print/ast_print_main.c.s

.PHONY : src/print/ast_print_main.s

# target to generate assembly for a file
src/print/ast_print_main.c.s:
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/print/ast_print_main.c.s
.PHONY : src/print/ast_print_main.c.s

src/utils/buffer.o: src/utils/buffer.c.o

.PHONY : src/utils/buffer.o

# target to build an object file
src/utils/buffer.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/utils/buffer.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/utils/buffer.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/utils/buffer.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/utils/buffer.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/utils/buffer.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/utils/buffer.c.o
.PHONY : src/utils/buffer.c.o

src/utils/buffer.i: src/utils/buffer.c.i

.PHONY : src/utils/buffer.i

# target to preprocess a source file
src/utils/buffer.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/utils/buffer.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/utils/buffer.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/utils/buffer.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/utils/buffer.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/utils/buffer.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/utils/buffer.c.i
.PHONY : src/utils/buffer.c.i

src/utils/buffer.s: src/utils/buffer.c.s

.PHONY : src/utils/buffer.s

# target to generate assembly for a file
src/utils/buffer.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/utils/buffer.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/utils/buffer.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/utils/buffer.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/utils/buffer.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/utils/buffer.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/utils/buffer.c.s
.PHONY : src/utils/buffer.c.s

src/utils/parser_utils.o: src/utils/parser_utils.c.o

.PHONY : src/utils/parser_utils.o

# target to build an object file
src/utils/parser_utils.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/utils/parser_utils.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/utils/parser_utils.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/utils/parser_utils.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/utils/parser_utils.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/utils/parser_utils.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/utils/parser_utils.c.o
.PHONY : src/utils/parser_utils.c.o

src/utils/parser_utils.i: src/utils/parser_utils.c.i

.PHONY : src/utils/parser_utils.i

# target to preprocess a source file
src/utils/parser_utils.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/utils/parser_utils.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/utils/parser_utils.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/utils/parser_utils.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/utils/parser_utils.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/utils/parser_utils.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/utils/parser_utils.c.i
.PHONY : src/utils/parser_utils.c.i

src/utils/parser_utils.s: src/utils/parser_utils.c.s

.PHONY : src/utils/parser_utils.s

# target to generate assembly for a file
src/utils/parser_utils.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/utils/parser_utils.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/utils/parser_utils.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/utils/parser_utils.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/utils/parser_utils.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/utils/parser_utils.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/utils/parser_utils.c.s
.PHONY : src/utils/parser_utils.c.s

src/utils/string_utils.o: src/utils/string_utils.c.o

.PHONY : src/utils/string_utils.o

# target to build an object file
src/utils/string_utils.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/utils/string_utils.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/utils/string_utils.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/utils/string_utils.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/utils/string_utils.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/utils/string_utils.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/utils/string_utils.c.o
.PHONY : src/utils/string_utils.c.o

src/utils/string_utils.i: src/utils/string_utils.c.i

.PHONY : src/utils/string_utils.i

# target to preprocess a source file
src/utils/string_utils.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/utils/string_utils.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/utils/string_utils.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/utils/string_utils.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/utils/string_utils.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/utils/string_utils.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/utils/string_utils.c.i
.PHONY : src/utils/string_utils.c.i

src/utils/string_utils.s: src/utils/string_utils.c.s

.PHONY : src/utils/string_utils.s

# target to generate assembly for a file
src/utils/string_utils.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/utils/string_utils.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/utils/string_utils.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/utils/string_utils.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/utils/string_utils.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/utils/string_utils.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/utils/string_utils.c.s
.PHONY : src/utils/string_utils.c.s

src/utils/xalloc.o: src/utils/xalloc.c.o

.PHONY : src/utils/xalloc.o

# target to build an object file
src/utils/xalloc.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/utils/xalloc.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/utils/xalloc.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/utils/xalloc.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/utils/xalloc.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/utils/xalloc.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/utils/xalloc.c.o
.PHONY : src/utils/xalloc.c.o

src/utils/xalloc.i: src/utils/xalloc.c.i

.PHONY : src/utils/xalloc.i

# target to preprocess a source file
src/utils/xalloc.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/utils/xalloc.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/utils/xalloc.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/utils/xalloc.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/utils/xalloc.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/utils/xalloc.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/utils/xalloc.c.i
.PHONY : src/utils/xalloc.c.i

src/utils/xalloc.s: src/utils/xalloc.c.s

.PHONY : src/utils/xalloc.s

# target to generate assembly for a file
src/utils/xalloc.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/utils/xalloc.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/utils/xalloc.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/utils/xalloc.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/utils/xalloc.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/utils/xalloc.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/utils/xalloc.c.s
.PHONY : src/utils/xalloc.c.s

src/var_storage/var_storage.o: src/var_storage/var_storage.c.o

.PHONY : src/var_storage/var_storage.o

# target to build an object file
src/var_storage/var_storage.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/var_storage/var_storage.c.o
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/var_storage/var_storage.c.o
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/var_storage/var_storage.c.o
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/var_storage/var_storage.c.o
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/var_storage/var_storage.c.o
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/var_storage/var_storage.c.o
.PHONY : src/var_storage/var_storage.c.o

src/var_storage/var_storage.i: src/var_storage/var_storage.c.i

.PHONY : src/var_storage/var_storage.i

# target to preprocess a source file
src/var_storage/var_storage.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/var_storage/var_storage.c.i
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/var_storage/var_storage.c.i
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/var_storage/var_storage.c.i
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/var_storage/var_storage.c.i
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/var_storage/var_storage.c.i
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/var_storage/var_storage.c.i
.PHONY : src/var_storage/var_storage.c.i

src/var_storage/var_storage.s: src/var_storage/var_storage.c.s

.PHONY : src/var_storage/var_storage.s

# target to generate assembly for a file
src/var_storage/var_storage.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/src/var_storage/var_storage.c.s
	$(MAKE) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/var_storage/var_storage.c.s
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/src/var_storage/var_storage.c.s
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/src/var_storage/var_storage.c.s
	$(MAKE) -f CMakeFiles/ast_print.dir/build.make CMakeFiles/ast_print.dir/src/var_storage/var_storage.c.s
	$(MAKE) -f CMakeFiles/token_printer.dir/build.make CMakeFiles/token_printer.dir/src/var_storage/var_storage.c.s
.PHONY : src/var_storage/var_storage.c.s

tests/tests_lexer.o: tests/tests_lexer.c.o

.PHONY : tests/tests_lexer.o

# target to build an object file
tests/tests_lexer.c.o:
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/tests/tests_lexer.c.o
.PHONY : tests/tests_lexer.c.o

tests/tests_lexer.i: tests/tests_lexer.c.i

.PHONY : tests/tests_lexer.i

# target to preprocess a source file
tests/tests_lexer.c.i:
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/tests/tests_lexer.c.i
.PHONY : tests/tests_lexer.c.i

tests/tests_lexer.s: tests/tests_lexer.c.s

.PHONY : tests/tests_lexer.s

# target to generate assembly for a file
tests/tests_lexer.c.s:
	$(MAKE) -f CMakeFiles/tests_lexer.dir/build.make CMakeFiles/tests_lexer.dir/tests/tests_lexer.c.s
.PHONY : tests/tests_lexer.c.s

tests/tests_parser.o: tests/tests_parser.c.o

.PHONY : tests/tests_parser.o

# target to build an object file
tests/tests_parser.c.o:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/tests/tests_parser.c.o
.PHONY : tests/tests_parser.c.o

tests/tests_parser.i: tests/tests_parser.c.i

.PHONY : tests/tests_parser.i

# target to preprocess a source file
tests/tests_parser.c.i:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/tests/tests_parser.c.i
.PHONY : tests/tests_parser.c.i

tests/tests_parser.s: tests/tests_parser.c.s

.PHONY : tests/tests_parser.s

# target to generate assembly for a file
tests/tests_parser.c.s:
	$(MAKE) -f CMakeFiles/tests_parser.dir/build.make CMakeFiles/tests_parser.dir/tests/tests_parser.c.s
.PHONY : tests/tests_parser.c.s

tests/tests_storage.o: tests/tests_storage.c.o

.PHONY : tests/tests_storage.o

# target to build an object file
tests/tests_storage.c.o:
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/tests/tests_storage.c.o
.PHONY : tests/tests_storage.c.o

tests/tests_storage.i: tests/tests_storage.c.i

.PHONY : tests/tests_storage.i

# target to preprocess a source file
tests/tests_storage.c.i:
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/tests/tests_storage.c.i
.PHONY : tests/tests_storage.c.i

tests/tests_storage.s: tests/tests_storage.c.s

.PHONY : tests/tests_storage.s

# target to generate assembly for a file
tests/tests_storage.c.s:
	$(MAKE) -f CMakeFiles/tests_storage.dir/build.make CMakeFiles/tests_storage.dir/tests/tests_storage.c.s
.PHONY : tests/tests_storage.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... 42sh"
	@echo "... ast_print"
	@echo "... tests_lexer"
	@echo "... tests_parser"
	@echo "... tests_storage"
	@echo "... token_printer"
	@echo "... src/ast/ast.o"
	@echo "... src/ast/ast.i"
	@echo "... src/ast/ast.s"
	@echo "... src/ast/free.o"
	@echo "... src/ast/free.i"
	@echo "... src/ast/free.s"
	@echo "... src/eval/ast_print.o"
	@echo "... src/eval/ast_print.i"
	@echo "... src/eval/ast_print.s"
	@echo "... src/eval/token_printer.o"
	@echo "... src/eval/token_printer.i"
	@echo "... src/eval/token_printer.s"
	@echo "... src/exec/commands.o"
	@echo "... src/exec/commands.i"
	@echo "... src/exec/commands.s"
	@echo "... src/exec/exec.o"
	@echo "... src/exec/exec.i"
	@echo "... src/exec/exec.s"
	@echo "... src/expansion/var_expansion.o"
	@echo "... src/expansion/var_expansion.i"
	@echo "... src/expansion/var_expansion.s"
	@echo "... src/lexer/lex_evaluation.o"
	@echo "... src/lexer/lex_evaluation.i"
	@echo "... src/lexer/lex_evaluation.s"
	@echo "... src/lexer/lexer.o"
	@echo "... src/lexer/lexer.i"
	@echo "... src/lexer/lexer.s"
	@echo "... src/lexer/token.o"
	@echo "... src/lexer/token.i"
	@echo "... src/lexer/token.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser/parser.o"
	@echo "... src/parser/parser.i"
	@echo "... src/parser/parser.s"
	@echo "... src/print/ast_print_dot.o"
	@echo "... src/print/ast_print_dot.i"
	@echo "... src/print/ast_print_dot.s"
	@echo "... src/print/ast_print_main.o"
	@echo "... src/print/ast_print_main.i"
	@echo "... src/print/ast_print_main.s"
	@echo "... src/utils/buffer.o"
	@echo "... src/utils/buffer.i"
	@echo "... src/utils/buffer.s"
	@echo "... src/utils/parser_utils.o"
	@echo "... src/utils/parser_utils.i"
	@echo "... src/utils/parser_utils.s"
	@echo "... src/utils/string_utils.o"
	@echo "... src/utils/string_utils.i"
	@echo "... src/utils/string_utils.s"
	@echo "... src/utils/xalloc.o"
	@echo "... src/utils/xalloc.i"
	@echo "... src/utils/xalloc.s"
	@echo "... src/var_storage/var_storage.o"
	@echo "... src/var_storage/var_storage.i"
	@echo "... src/var_storage/var_storage.s"
	@echo "... tests/tests_lexer.o"
	@echo "... tests/tests_lexer.i"
	@echo "... tests/tests_lexer.s"
	@echo "... tests/tests_parser.o"
	@echo "... tests/tests_parser.i"
	@echo "... tests/tests_parser.s"
	@echo "... tests/tests_storage.o"
	@echo "... tests/tests_storage.i"
	@echo "... tests/tests_storage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

