.TH "src/history Directory Reference" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/history Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBauto_completion\&.c\fP"
.br
.ti -1c
.RI "file \fBhistory\&.c\fP"
.br
.ti -1c
.RI "file \fBhistory\&.h\fP"
.br
.RI "History functions\&. "
.in -1c
