.TH "src Directory Reference" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBast\fP"
.br
.ti -1c
.RI "directory \fBexec\fP"
.br
.ti -1c
.RI "directory \fBexpansion\fP"
.br
.ti -1c
.RI "directory \fBgarbage_collector\fP"
.br
.ti -1c
.RI "directory \fBhistory\fP"
.br
.ti -1c
.RI "directory \fBlexer\fP"
.br
.ti -1c
.RI "directory \fBparser\fP"
.br
.ti -1c
.RI "directory \fBprint\fP"
.br
.ti -1c
.RI "directory \fBstorage\fP"
.br
.ti -1c
.RI "directory \fButils\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBmain\&.h\fP"
.br
.in -1c
