.TH "src/var_storage Directory Reference" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/var_storage Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBvar_storage\&.c\fP"
.br
.ti -1c
.RI "file \fBvar_storage\&.h\fP"
.br
.RI "Var storage structures and functions\&. "
.in -1c
