.TH "src/utils Directory Reference" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbracket_counter\&.c\fP"
.br
.ti -1c
.RI "file \fBbracket_counter\&.h\fP"
.br
.ti -1c
.RI "file \fBbuffer\&.c\fP"
.br
.ti -1c
.RI "file \fBbuffer\&.h\fP"
.br
.RI "Buffer structure and functions\&. "
.ti -1c
.RI "file \fBindex_utils\&.c\fP"
.br
.ti -1c
.RI "file \fBindex_utils\&.h\fP"
.br
.RI "Index functions\&. "
.ti -1c
.RI "file \fBmain_utils\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_itoa\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_itoa\&.h\fP"
.br
.ti -1c
.RI "file \fBparser_utils\&.c\fP"
.br
.ti -1c
.RI "file \fBparser_utils\&.h\fP"
.br
.ti -1c
.RI "file \fBstring_utils\&.c\fP"
.br
.ti -1c
.RI "file \fBstring_utils\&.h\fP"
.br
.RI "String usage functions\&. "
.ti -1c
.RI "file \fBxalloc\&.c\fP"
.br
.ti -1c
.RI "file \fBxalloc\&.h\fP"
.br
.RI "Special allocation functions\&. "
.in -1c
