.TH "src/expansion/arithmetic Directory Reference" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/expansion/arithmetic Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBast\fP"
.br
.ti -1c
.RI "directory \fBexec\fP"
.br
.ti -1c
.RI "directory \fBlexer\fP"
.br
.ti -1c
.RI "directory \fBparser\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBarithmetic_ast\&.c\fP"
.br
.ti -1c
.RI "file \fBarithmetic_ast\&.h\fP"
.br
.in -1c
