.TH "src/ast Directory Reference" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ast Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBast\&.c\fP"
.br
.ti -1c
.RI "file \fBast\&.h\fP"
.br
.RI "Define ast and parser structures\&. "
.ti -1c
.RI "file \fBfree\&.c\fP"
.br
.ti -1c
.RI "file \fBfree\&.h\fP"
.br
.RI "Free functions\&. "
.in -1c
