.TH "src/expansion/arithmetic/lexer Directory Reference" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/expansion/arithmetic/lexer Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBarithmetic_lexer\&.c\fP"
.br
.ti -1c
.RI "file \fBarithmetic_lexer\&.h\fP"
.br
.ti -1c
.RI "file \fBarithmetic_token\&.c\fP"
.br
.ti -1c
.RI "file \fBarithmetic_token\&.h\fP"
.br
.in -1c
