.TH "src/expansion Directory Reference" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/expansion Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcommand_substitution\&.c\fP"
.br
.ti -1c
.RI "file \fBexpansion\&.c\fP"
.br
.ti -1c
.RI "file \fBexpansion\&.h\fP"
.br
.RI "Var storage structures and functions\&. "
.ti -1c
.RI "file \fBmy_popen\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_popen\&.h\fP"
.br
.RI "Function for command substitution\&. "
.ti -1c
.RI "file \fBtilde_expansion\&.c\fP"
.br
.ti -1c
.RI "file \fBvar_expansion\&.c\fP"
.br
.in -1c
