.TH "src/expansion/arithmetic/parser Directory Reference" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/expansion/arithmetic/parser Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBarithmetic_parser\&.c\fP"
.br
.ti -1c
.RI "file \fBarithmetic_parser\&.h\fP"
.br
.in -1c
