.TH "src/builtins Directory Reference" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbuiltins\&.c\fP"
.br
.ti -1c
.RI "file \fBbuiltins\&.h\fP"
.br
.RI "Builtin functions\&. "
.in -1c
