.TH "src/expansion/arithmetic_expansion.c" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/expansion/arithmetic_expansion.c
.SH SYNOPSIS
.br
.PP
\fC#include 'expansion\&.h'\fP
.br
\fC#include '\&.\&./utils/string_utils\&.h'\fP
.br
\fC#include '\&.\&./utils/xalloc\&.h'\fP
.br
\fC#include '\&.\&./utils/buffer\&.h'\fP
.br
\fC#include '\&.\&./utils/index_utils\&.h'\fP
.br
\fC#include '\&.\&./utils/bracket_counter\&.h'\fP
.br
\fC#include '\&.\&./utils/my_itoa\&.h'\fP
.br
\fC#include '\&./arithmetic/lexer/arithmetic_lexer\&.h'\fP
.br
\fC#include '\&./arithmetic/ast/arithmetic_ast\&.h'\fP
.br
\fC#include '\&./arithmetic/parser/arithmetic_parser\&.h'\fP
.br
\fC#include '\&./arithmetic/exec/arithmetic_execution\&.h'\fP
.br
\fC#include 'my_popen\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBperform_arithmetic_substitution\fP (char *word)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* perform_arithmetic_substitution (char * word)"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
