.TH "arithmetic_token" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arithmetic_token
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arithmetic_token\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBarithmetic_token_type\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "struct \fBarithmetic_token\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBarithmetic_token\fP* next"

.SS "enum \fBarithmetic_token_type\fP type"

.SS "int value"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
