.TH "src/expansion/arithmetic/exec/arithmetic_execution.c" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/expansion/arithmetic/exec/arithmetic_execution.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./exec/arithmetic_execution\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_pow\fP (int n, int p)"
.br
.ti -1c
.RI "int \fBto_int\fP (double x)"
.br
.ti -1c
.RI "double \fBexec_arithmetic_ast\fP (struct \fBarithmetic_ast\fP *ast, bool *\fBerror\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double exec_arithmetic_ast (struct \fBarithmetic_ast\fP * ast, bool * error)"

.SS "int my_pow (int n, int p)"

.SS "int to_int (double x)"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
