.TH "src/expansion/arithmetic/exec/arithmetic_execution.h" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/expansion/arithmetic/exec/arithmetic_execution.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./ast/arithmetic_ast\&.h'\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBexec_arithmetic_ast\fP (struct \fBarithmetic_ast\fP *ast, bool *\fBerror\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double exec_arithmetic_ast (struct \fBarithmetic_ast\fP * ast, bool * error)"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
