.TH "arithmetic_token_list" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arithmetic_token_list
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arithmetic_lexer\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBarithmetic_token\fP * \fBlast\fP"
.br
.ti -1c
.RI "struct \fBarithmetic_token\fP * \fBfirst\fP"
.br
.ti -1c
.RI "struct \fBarithmetic_token\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBarithmetic_token\fP* first"

.SS "struct \fBarithmetic_token\fP* last"

.SS "struct \fBarithmetic_token\fP* next"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
