.TH "src/utils/attr.h" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/attr.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBATTR\fP(Att)   __attribute__((Att))"
.br
.ti -1c
.RI "#define \fB__malloc\fP   \fBATTR\fP(malloc)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __malloc   \fBATTR\fP(malloc)"

.SS "#define ATTR(Att)   __attribute__((Att))"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
