.TH "src/utils/bracket_counter.c" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/bracket_counter.c
.SH SYNOPSIS
.br
.PP
\fC#include 'bracket_counter\&.h'\fP
.br
\fC#include '\&.\&./utils/buffer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcount_closed_occurences\fP (char *s, size_t i, enum \fBcountable\fP \fBcountable\fP)"
.br
.ti -1c
.RI "bool \fBcheck_closing_symbols\fP (char *s)"
.br
.ti -1c
.RI "bool \fBcheck_closing_symbols_from_splitted\fP (char **splitted, int i)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool check_closing_symbols (char * s)"

.SS "bool check_closing_symbols_from_splitted (char ** splitted, int i)"

.SS "int count_closed_occurences (char * s, size_t i, enum \fBcountable\fP \fBcountable\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
