.TH "buffer" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
buffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <buffer\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBbuf\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* buf"

.SS "int index"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
