.TH "src/module/builtins.c" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/module/builtins.c
.SH SYNOPSIS
.br
.PP
\fC#include 'module\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBparse_export\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool parse_export ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
