.TH "commands" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
commands
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exec\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "void(* \fBfunction\fP )(char **args)"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void(* function) (char **args)"

.SS "const char* name"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
