.TH "src/exec/commands.c" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/exec/commands.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <wordexp\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <err\&.h>\fP
.br
\fC#include 'commands\&.h'\fP
.br
\fC#include '\&.\&./parser/parser\&.h'\fP
.br
\fC#include '\&./utils/xalloc\&.h'\fP
.br
\fC#include '\&.\&./exec/exec\&.h'\fP
.br
\fC#include '\&.\&./expansion/expansion\&.h'\fP
.br
\fC#include '\&.\&./storage/var_storage\&.h'\fP
.br
\fC#include '\&.\&./storage/program_data_storage\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_DEFAULT_SOURCE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdelete_alias\fP (char **args)"
.br
.RI "function to delete an alias "
.ti -1c
.RI "void \fBcreate_alias\fP (char **args)"
.br
.RI "function to create an alias "
.ti -1c
.RI "bool \fBload_file\fP (char *path, bool warning)"
.br
.RI "function to give a file to the 42sh "
.ti -1c
.RI "void \fBsource\fP (char **args)"
.br
.RI "implementation of command sourcefnac "
.ti -1c
.RI "int \fBprint_without_sp\fP (char *c)"
.br
.ti -1c
.RI "void \fBecho\fP (char **args)"
.br
.RI "implementation of command echo "
.ti -1c
.RI "void \fBcd\fP (char **args)"
.br
.ti -1c
.RI "void \fBexport\fP (char **args)"
.br
.RI "implementation of command export "
.ti -1c
.RI "void \fBexit_shell\fP (void)"
.br
.RI "implementation of exit_shell "
.ti -1c
.RI "void \fBfunc_continue\fP (char **args)"
.br
.RI "Particular print with option -e from echo\&. "
.ti -1c
.RI "void \fBfunc_break\fP (char **args)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _DEFAULT_SOURCE"

.SH "Function Documentation"
.PP 
.SS "void cd (char ** args)"

.PP
\fBParameters\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void create_alias (char ** args)"

.PP
function to create an alias 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void delete_alias (char ** args)"

.PP
function to delete an alias 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void echo (char ** args)"

.PP
implementation of command echo 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void exit_shell (void)"

.PP
implementation of exit_shell 
.SS "void export (char ** args)"

.PP
implementation of command export 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void func_break (char ** args)"

.SS "void func_continue (char ** args)"

.PP
Particular print with option -e from echo\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SS "bool load_file (char * path, bool warning)"

.PP
function to give a file to the 42sh 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 
.br
\fIwarning\fP 
.RE
.PP
\fBReturns\fP
.RS 4
true 
.PP
false 
.RE
.PP

.SS "int print_without_sp (char * c)"

.SS "void source (char ** args)"

.PP
implementation of command sourcefnac 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
