.TH "command_break" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
command_break
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exec\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBis_break\fP"
.br
.ti -1c
.RI "bool \fBfrom_loop\fP"
.br
.ti -1c
.RI "int \fBcurrent_loop\fP"
.br
.ti -1c
.RI "int \fBtime_to_loop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Global for breakcommand 
.SH "Field Documentation"
.PP 
.SS "int current_loop"

.SS "bool from_loop"

.SS "bool is_break"

.SS "int time_to_loop"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
