.TH "src/exec/commands.h" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/exec/commands.h \- Extra commands functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBecho_tab\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBecho\fP (char **args)"
.br
.RI "implementation of command echo "
.ti -1c
.RI "void \fBcd\fP (char **args)"
.br
.RI "implementation of command cd "
.ti -1c
.RI "void \fBexport\fP (char **args)"
.br
.RI "implementation of command export "
.ti -1c
.RI "void \fBexit_shell\fP (char **args)"
.br
.RI "implementation of exit_shell "
.in -1c
.SH "Detailed Description"
.PP 
Extra commands functions\&. 


.PP
\fBAuthor:\fP
.RS 4
Team 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2020-05-03
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void cd (char ** args)"

.PP
implementation of command cd 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void echo (char ** args)"

.PP
implementation of command echo 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void exit_shell (char ** args)"

.PP
implementation of exit_shell 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void export (char ** args)"

.PP
implementation of command export 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
