.TH "src/exec/commands.h" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/exec/commands.h \- Extra commands functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBecho_tab\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUNALIAS_USAGE\fP   'unalias: usage: unalias [\-a] name [name \&.\&.\&.]\\n'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdelete_alias\fP (char **args)"
.br
.RI "function to delete an alias "
.ti -1c
.RI "void \fBcreate_alias\fP (char **args)"
.br
.RI "function to create an alias "
.ti -1c
.RI "bool \fBload_file\fP (char *path, bool warning)"
.br
.RI "function to give a file to the 42sh "
.ti -1c
.RI "void \fBsource\fP (char **args)"
.br
.RI "implementation of command sourcefnac "
.ti -1c
.RI "void \fBecho\fP (char **args)"
.br
.RI "implementation of command echo "
.ti -1c
.RI "void \fBcd\fP (char **args)"
.br
.ti -1c
.RI "void \fBexport\fP (char **args)"
.br
.RI "implementation of command export "
.ti -1c
.RI "void \fBexit_shell\fP (void)"
.br
.RI "implementation of exit_shell "
.ti -1c
.RI "void \fBprint_args\fP (char **args)"
.br
.RI "Print all argson stdout\&. "
.ti -1c
.RI "int \fBprint_without_sp\fP (char *c)"
.br
.RI "Particular print with option -e from echo\&. "
.ti -1c
.RI "void \fBprint_echo\fP (char **args, bool e, bool n)"
.br
.RI "Echo function\&. "
.ti -1c
.RI "void \fBfunc_continue\fP (char **args)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char ** \fBenviron\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Extra commands functions\&. 


.PP
\fBAuthor:\fP
.RS 4
Team 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2020-05-03
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define UNALIAS_USAGE   'unalias: usage: unalias [\-a] name [name \&.\&.\&.]\\n'"

.SH "Function Documentation"
.PP 
.SS "void cd (char ** args)"

.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void create_alias (char ** args)"

.PP
function to create an alias 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void delete_alias (char ** args)"

.PP
function to delete an alias 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void echo (char ** args)"

.PP
implementation of command echo 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void exit_shell (void)"

.PP
implementation of exit_shell 
.SS "void export (char ** args)"

.PP
implementation of command export 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void func_continue (char ** args)"

.SS "bool load_file (char * path, bool warning)"

.PP
function to give a file to the 42sh 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP 
.br
\fIwarning\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true 
.PP
false 
.RE
.PP

.SS "void print_args (char ** args)"

.PP
Print all argson stdout\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SS "void print_echo (char ** args, bool e, bool n)"

.PP
Echo function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.br
\fIe\fP 
.br
\fIn\fP 
.RE
.PP

.SS "int print_without_sp (char * c)"

.PP
Particular print with option -e from echo\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.SS "void source (char ** args)"

.PP
implementation of command sourcefnac 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "char** environ"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
