.TH "src/expansion/command_substitution.c" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/expansion/command_substitution.c
.SH SYNOPSIS
.br
.PP
\fC#include 'expansion\&.h'\fP
.br
\fC#include '\&.\&./utils/string_utils\&.h'\fP
.br
\fC#include '\&.\&./utils/xalloc\&.h'\fP
.br
\fC#include '\&.\&./utils/buffer\&.h'\fP
.br
\fC#include '\&.\&./utils/index_utils\&.h'\fP
.br
\fC#include '\&.\&./utils/bracket_counter\&.h'\fP
.br
\fC#include 'my_popen\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBperform_command_substitution\fP (char *word)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* perform_command_substitution (char * word)"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
