.TH "command_continue" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
command_continue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exec\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBis_continue\fP"
.br
.ti -1c
.RI "int \fBtime_to_loop\fP"
.br
.ti -1c
.RI "bool \fBfrom_loop\fP"
.br
.ti -1c
.RI "int \fBcurrent_loop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Global for continue command 
.SH "Field Documentation"
.PP 
.SS "int current_loop"

.SS "bool from_loop"

.SS "bool is_continue"

.SS "int time_to_loop"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
