.TH "src/exec/exec_for.c" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/exec/exec_for.c
.SH SYNOPSIS
.br
.PP
\fC#include 'exec\&.h'\fP
.br
\fC#include '\&.\&./ast/ast\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBperform_for_range\fP (struct \fBrange\fP *r, struct \fBnode_for\fP *ast)"
.br
.RI "for function to execute different range "
.ti -1c
.RI "bool \fBperform_for_enumeration\fP (struct \fBnode_for\fP *ast, int len_range)"
.br
.RI "for function to perform enumeration "
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool perform_for_enumeration (struct \fBnode_for\fP * ast, int len_range)"

.PP
for function to perform enumeration 
.PP
\fBParameters:\fP
.RS 4
\fIast\fP 
.br
\fIlen_range\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true 
.PP
false 
.RE
.PP

.SS "int perform_for_range (struct \fBrange\fP * r, struct \fBnode_for\fP * ast)"

.PP
for function to execute different range 
.PP
\fBParameters:\fP
.RS 4
\fIr\fP 
.br
\fIast\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
