.TH "src/expansion/expansion.c" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/expansion/expansion.c
.SH SYNOPSIS
.br
.PP
\fC#include 'expansion\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBsubstitute\fP (char *word)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* substitute (char * word)"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
