.TH "file_manager" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_manager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <redirection\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsave_in\fP"
.br
.ti -1c
.RI "int \fBsave_out\fP"
.br
.ti -1c
.RI "int \fBsave_err\fP"
.br
.ti -1c
.RI "int \fBfd_to_close\fP"
.br
.ti -1c
.RI "FILE * \fBfile\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int fd_to_close"

.SS "FILE* file"

.SS "int save_err"

.SS "int save_in"

.SS "int save_out"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
