.TH "src/garbage_collector/garbage_collector.c" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/garbage_collector/garbage_collector.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'garbage_collector\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnew_garbage_collector\fP (void)"
.br
.RI "create the garbage collector "
.ti -1c
.RI "void \fBappend_to_garbage\fP (void *addr)"
.br
.RI "append addr to list of elements "
.ti -1c
.RI "void \fBfree_garbage_collector\fP (void)"
.br
.RI "free list of elements "
.ti -1c
.RI "void \fBprint_garbage_collector\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBgarbage_collector\fP * \fBgarbage_collector\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void append_to_garbage (void * addr)"

.PP
append addr to list of elements 
.PP
\fBParameters\fP
.RS 4
\fIaddr\fP 
.RE
.PP

.SS "void free_garbage_collector ()"

.PP
free list of elements 
.SS "void new_garbage_collector (void)"

.PP
create the garbage collector 
.SS "void print_garbage_collector (void)"

.SH "Variable Documentation"
.PP 
.SS "struct \fBgarbage_collector\fP* \fBgarbage_collector\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
