.TH "garbage_collector_variable" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
garbage_collector_variable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <garbage_collector\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBgarbage_variable\fP * \fBfirst\fP"
.br
.ti -1c
.RI "struct \fBgarbage_variable\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBgarbage_variable\fP * \fBlast\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBgarbage_variable\fP* first"

.SS "struct \fBgarbage_variable\fP* last"

.SS "struct \fBgarbage_variable\fP* next"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
