.TH "history" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
history
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <history\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char ** \fBcommands\fP"
.br
.ti -1c
.RI "int \fBnb_commands\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "int \fBnb_lines\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char** \fBcommands\fP"

.SS "int index"

.SS "int nb_commands"

.SS "int nb_lines"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
