.TH "lexer" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lexer \- Lexer architecture and methods\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lexer\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBinput\fP"
.br
.ti -1c
.RI "struct \fBtoken_list\fP * \fBtoken_list\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Lexer architecture and methods\&. 


.PP
\fBParameters:\fP
.RS 4
\fIinput\fP the full input string\&. 
.br
\fI\fBtoken_list\fP\fP the linked-list of tokens\&. 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "char* input"

.SS "struct \fBtoken_list\fP* \fBtoken_list\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
