.TH "src/main.c" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&./main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_option_sh\fP (void)"
.br
.ti -1c
.RI "int \fBmain\fP (int ac, char **av)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBoption_sh\fP * \fBoption\fP"
.br
.ti -1c
.RI "struct \fBvar_storage\fP * \fBalias_storage\fP"
.br
.ti -1c
.RI "struct \fBvar_storage\fP * \fBvar_storage\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void init_option_sh (void)"

.SS "int main (int ac, char ** av)"

.SH "Variable Documentation"
.PP 
.SS "struct \fBvar_storage\fP* alias_storage"

.SS "struct \fBoption_sh\fP* option"

.SS "struct \fBvar_storage\fP* \fBvar_storage\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
