.TH "src/main.h" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBoption_sh\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSAGE\fP   'Usage : \&./42sh [GNU long option] [option] [file]\\n'"
.br
.ti -1c
.RI "#define \fBSTART_COLOR\fP   '\\033'"
.br
.ti -1c
.RI "#define \fBCYAN\fP   '36m'"
.br
.ti -1c
.RI "#define \fBBLINK\fP   '\\033[5m'"
.br
.ti -1c
.RI "#define \fBEND_COLOR\fP   '\\033[0m'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BLINK   '\\033[5m'"

.SS "#define CYAN   '36m'"

.SS "#define END_COLOR   '\\033[0m'"

.SS "#define START_COLOR   '\\033'"

.SS "#define USAGE   'Usage : \&./42sh [GNU long option] [option] [file]\\n'"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
