.TH "src/main.c" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&./main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBoption_sh\fP * \fBinit_option_sh\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int ac, char **av)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct \fBoption_sh\fP* init_option_sh (void)"

.SS "int main (int ac, char ** av)"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
