.TH "src/utils/my_itoa.c" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/my_itoa.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBnumber_digits\fP (int n)"
.br
.ti -1c
.RI "int \fBpower\fP (int x, int y)"
.br
.ti -1c
.RI "char * \fBmy_itoa\fP (int value, char *s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_itoa (int value, char * s)"

.SS "int number_digits (int n)"

.SS "int power (int x, int y)"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
