.TH "node_do_group" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_do_group
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBnode_compound_list\fP * \fBbody\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode_compound_list\fP* body"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
