.TH "node_prefix::prefix" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_prefix::prefix
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBassigment_word\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBnode_prefix::prefix::assigment_word\fP * \fBassigment_word\fP"
.br
.ti -1c
.RI "struct \fBnode_redirection\fP * \fBredirection\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode_prefix::prefix::assigment_word\fP * \fBassigment_word\fP"

.SS "struct \fBnode_redirection\fP* redirection"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
