.TH "node_redirection" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_redirection
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBtype\fP"
.br
.ti -1c
.RI "char * \fBleft\fP"
.br
.ti -1c
.RI "char * \fBright\fP"
.br
.ti -1c
.RI "struct \fBnode_redirection\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* left"

.SS "struct \fBnode_redirection\fP* next"

.SS "char* right"

.SS "unsigned int type"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
