.TH "node_element::element" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_element::element
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBword\fP"
.br
.ti -1c
.RI "struct \fBnode_redirection\fP * \fBredirection\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode_redirection\fP* redirection"

.SS "char* word"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
