.TH "node_command::command" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_command::command
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBnode_simple_command\fP * \fBsimple_command\fP"
.br
.ti -1c
.RI "struct \fBnode_shell_command\fP * \fBshell_command\fP"
.br
.ti -1c
.RI "struct \fBnode_funcdec\fP * \fBfuncdec\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode_funcdec\fP* funcdec"

.SS "struct \fBnode_shell_command\fP* shell_command"

.SS "struct \fBnode_simple_command\fP* simple_command"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
