.TH "node_compound_list" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_compound_list
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBnode_and_or\fP * \fBand_or\fP"
.br
.ti -1c
.RI "struct \fBnode_compound_list\fP * \fBnext_sibling\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode_and_or\fP* and_or"

.SS "struct \fBnode_compound_list\fP* next_sibling"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
