.TH "node_input" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_input
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBnode_list\fP * \fBnode_list\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode_list\fP* \fBnode_list\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
