.TH "node_prefix::prefix::assigment_word" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_prefix::prefix::assigment_word
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBvariable_name\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* value"

.SS "char* variable_name"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
