.TH "node_for" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_for
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBvariable_name\fP"
.br
.ti -1c
.RI "struct \fBrange\fP * \fBrange\fP"
.br
.ti -1c
.RI "struct \fBnode_do_group\fP * \fBbody\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode_do_group\fP* body"

.SS "struct \fBrange\fP* \fBrange\fP"

.SS "char* variable_name"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
