.TH "node_shell_command::shell" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_shell_command::shell
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBnode_compound_list\fP * \fBcompound_list\fP"
.br
.ti -1c
.RI "struct \fBnode_for\fP * \fBrule_for\fP"
.br
.ti -1c
.RI "struct \fBnode_while\fP * \fBrule_while\fP"
.br
.ti -1c
.RI "struct \fBnode_until\fP * \fBrule_until\fP"
.br
.ti -1c
.RI "struct \fBnode_case\fP * \fBrule_case\fP"
.br
.ti -1c
.RI "struct \fBnode_if\fP * \fBrule_if\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode_compound_list\fP* compound_list"

.SS "struct \fBnode_case\fP* rule_case"

.SS "struct \fBnode_for\fP* rule_for"

.SS "struct \fBnode_if\fP* rule_if"

.SS "struct \fBnode_until\fP* rule_until"

.SS "struct \fBnode_while\fP* rule_while"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
