.TH "node_simple_command" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_simple_command
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBto_export\fP"
.br
.ti -1c
.RI "bool \fBto_alias\fP"
.br
.ti -1c
.RI "struct \fBnode_prefix\fP * \fBprefixes\fP"
.br
.ti -1c
.RI "struct \fBnode_element\fP * \fBelements\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode_element\fP* elements"

.SS "struct \fBnode_prefix\fP* prefixes"

.SS "bool to_alias"

.SS "bool to_export"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
