.TH "node_case_item" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_case_item
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBword_list\fP * \fBwords\fP"
.br
.ti -1c
.RI "struct \fBnode_compound_list\fP * \fBcompound_list\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode_compound_list\fP* compound_list"

.SS "struct \fBword_list\fP* words"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
