.TH "node_shell_command" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_shell_command
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBshell\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBtype_clause\fP { \fBC_BRACKETS\fP, \fBPARENTHESIS\fP, \fBRULE\fP }"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBnode_shell_command::type_clause\fP \fBtype\fP"
.br
.ti -1c
.RI "union \fBnode_shell_command::shell\fP \fBshell\fP"
.br
.ti -1c
.RI "enum \fBshell_type\fP \fBshell_type\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBtype_clause\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIC_BRACKETS \fP\fP
.TP
\fB\fIPARENTHESIS \fP\fP
.TP
\fB\fIRULE \fP\fP
.SH "Field Documentation"
.PP 
.SS "union \fBnode_shell_command::shell\fP \fBshell\fP"

.SS "enum \fBshell_type\fP \fBshell_type\fP"

.SS "enum \fBnode_shell_command::type_clause\fP type"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
