.TH "node_case_clause" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_case_clause
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBnode_case_item\fP * \fBcase_item\fP"
.br
.ti -1c
.RI "struct \fBnode_case_clause\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode_case_item\fP* case_item"

.SS "struct \fBnode_case_clause\fP* next"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
