.TH "node_funcdec" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_funcdec
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBis_function\fP"
.br
.ti -1c
.RI "char * \fBfunction_name\fP"
.br
.ti -1c
.RI "struct \fBnode_shell_command\fP * \fBshell_command\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* function_name"

.SS "bool is_function"

.SS "struct \fBnode_shell_command\fP* shell_command"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
