.TH "node_and_or::left" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_and_or::left
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBnode_pipeline\fP * \fBpipeline\fP"
.br
.ti -1c
.RI "struct \fBnode_and_or\fP * \fBand_or\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode_and_or\fP* and_or"

.SS "struct \fBnode_pipeline\fP* pipeline"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
