.TH "node_case" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_case
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBis_case_clause\fP"
.br
.ti -1c
.RI "char * \fBword\fP"
.br
.ti -1c
.RI "struct \fBnode_case_clause\fP * \fBcase_clause\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode_case_clause\fP* case_clause"

.SS "bool is_case_clause"

.SS "char* word"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
