.TH "option_sh" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
option_sh
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBnorc_flag\fP"
.br
.ti -1c
.RI "bool \fBprint_ast_flag\fP"
.br
.ti -1c
.RI "bool \fBshotp\fP"
.br
.ti -1c
.RI "char * \fBcmd\fP"
.br
.ti -1c
.RI "char * \fBfile_path\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* cmd"

.SS "char* file_path"

.SS "bool norc_flag"

.SS "bool print_ast_flag"

.SS "bool shotp"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
