.TH "src/storage/program_data_storage.h" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/storage/program_data_storage.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBprogram_data_storage\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnew_program_data_storage\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "void \fBappend_program_data\fP (char *element)"
.br
.ti -1c
.RI "void \fBfree_program_data_storage\fP (void)"
.br
.ti -1c
.RI "void \fBupdate_last_status\fP (int status)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBprogram_data_storage\fP * \fBprogram_data\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void append_program_data (char * element)"

.SS "void free_program_data_storage (void)"

.SS "void new_program_data_storage (int argc, char * argv[])"

.SS "void update_last_status (int status)"

.SH "Variable Documentation"
.PP 
.SS "struct \fBprogram_data_storage\fP* program_data"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
