.TH "program_data_storage" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
program_data_storage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <program_data_storage\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBbinary_name\fP"
.br
.ti -1c
.RI "char ** \fBargv\fP"
.br
.ti -1c
.RI "int \fBargc\fP"
.br
.ti -1c
.RI "char * \fBlast_cmd_status\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int argc"

.SS "char** argv"

.SS "char* binary_name"

.SS "char* last_cmd_status"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
