.TH "range" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
range
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBvalue\fP"
.br
.ti -1c
.RI "struct \fBrange\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBrange\fP* next"

.SS "char* value"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
