.TH "std" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exec\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBin\fP"
.br
.ti -1c
.RI "char * \fBout\fP"
.br
.ti -1c
.RI "char * \fBerr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* err"

.SS "char* in"

.SS "char* out"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
