.TH "src/utils/string_utils.c" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/string_utils.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include '\&.\&./utils/string_utils\&.h'\fP
.br
\fC#include '\&.\&./utils/xalloc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBtype_to_str\fP (int type)"
.br
.RI "Return the associated string of a token type\&. "
.ti -1c
.RI "int \fBis\fP (const char *a, const char *b)"
.br
.RI "Return true is a == b\&. "
.ti -1c
.RI "int \fBis_number\fP (char c)"
.br
.RI "Return true is c is a number\&. "
.ti -1c
.RI "char * \fBsubstr\fP (char *src, int pos, int len)"
.br
.RI "Return the substring between pos and len - 1\&. "
.ti -1c
.RI "char * \fBmy_strdup\fP (const char *c)"
.br
.ti -1c
.RI "void \fBerror\fP (char *msg)"
.br
.RI "Print an error in stderr when an invalid token appeared\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void error (char * msg)"

.PP
Print an error in stderr when an invalid token appeared\&. 
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP the message to display\&. 
.RE
.PP

.SS "int is (const char * a, const char * b)"

.PP
Return true is a == b\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP the first string to be compared\&. 
.br
\fIb\fP the decond string to be compared\&. 
.RE
.PP

.SS "int is_number (char c)"

.PP
Return true is c is a number\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP the caracter\&. 
.RE
.PP

.SS "char* my_strdup (const char * c)"

.SS "char* substr (char * src, int pos, int len)"

.PP
Return the substring between pos and len - 1\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsrc\fP the string\&. 
.br
\fIpos\fP the starting index\&. 
.br
\fIlen\fP the ending index\&. 
.RE
.PP

.SS "char* type_to_str (int type)"

.PP
Return the associated string of a token type\&. 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP the enum value of the token\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
