.TH "tab_redi" 3 "Mon May 4 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tab_redi
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exec\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBstd\fP \fBdless\fP"
.br
.ti -1c
.RI "struct \fBstd\fP \fBlessgreat\fP"
.br
.ti -1c
.RI "struct \fBstd\fP \fBlessand\fP"
.br
.ti -1c
.RI "struct \fBstd\fP \fBless\fP"
.br
.ti -1c
.RI "struct \fBstd\fP \fBdgreat\fP"
.br
.ti -1c
.RI "struct \fBstd\fP \fBgreatand\fP"
.br
.ti -1c
.RI "struct \fBstd\fP \fBclobber\fP"
.br
.ti -1c
.RI "struct \fBstd\fP \fBgreat\fP"
.br
.ti -1c
.RI "struct \fBstd\fP \fBdlessdash\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBstd\fP clobber"

.SS "struct \fBstd\fP dgreat"

.SS "struct \fBstd\fP dless"

.SS "struct \fBstd\fP dlessdash"

.SS "struct \fBstd\fP great"

.SS "struct \fBstd\fP greatand"

.SS "struct \fBstd\fP less"

.SS "struct \fBstd\fP lessand"

.SS "struct \fBstd\fP lessgreat"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
