.TH "tab_redirection" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tab_redirection
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <redirection\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBstd\fP \fBredirections\fP [\fBTAB_REDI_SIZE\fP]"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBstd\fP redirections[\fBTAB_REDI_SIZE\fP]"

.SS "int size"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
