.TH "tests/tests_history.c" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/tests_history.c
.SH SYNOPSIS
.br
.PP
\fC#include <criterion/criterion\&.h>\fP
.br
\fC#include 'history/history\&.h'\fP
.br
\fC#include 'utils/string_utils\&.h'\fP
.br
\fC#include 'garbage_collector/garbage_collector\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (\fBhistory\fP, basic)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Test (\fBhistory\fP, basic)"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
