.TH "tests/tests_ast.c" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/tests_ast.c
.SH SYNOPSIS
.br
.PP
\fC#include <criterion/criterion\&.h>\fP
.br
\fC#include 'lexer/lexer\&.h'\fP
.br
\fC#include 'ast/ast\&.h'\fP
.br
\fC#include 'utils/string_utils\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
