.TH "tests/tests_bultins.c" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/tests_bultins.c
.SH SYNOPSIS
.br
.PP
\fC#include <criterion/criterion\&.h>\fP
.br
\fC#include '\&.\&./exec/commands\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (\fBexport\fP, simple_export)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Test (\fBexport\fP, simple_export)"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
