.TH "tests/tests_var_expansion.c" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/tests_var_expansion.c
.SH SYNOPSIS
.br
.PP
\fC#include <criterion/criterion\&.h>\fP
.br
\fC#include 'expansion/expansion\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (\fBvar_storage\fP, basic_operation)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBvar_storage\fP * \fBalias_storage\fP"
.br
.ti -1c
.RI "struct \fBvar_storage\fP * \fBvar_storage\fP"
.br
.ti -1c
.RI "struct \fBfile_manager\fP * \fBfile_manager\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Test (\fBvar_storage\fP, basic_operation)"

.SH "Variable Documentation"
.PP 
.SS "struct \fBvar_storage\fP* alias_storage"

.SS "struct \fBfile_manager\fP* \fBfile_manager\fP"

.SS "struct \fBvar_storage\fP* \fBvar_storage\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
