.TH "token_list" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
token_list \- Basically a lined-list of tokens\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <token\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBtoken\fP * \fBlast\fP"
.br
.ti -1c
.RI "struct \fBtoken\fP * \fBfirst\fP"
.br
.ti -1c
.RI "struct \fBtoken\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basically a lined-list of tokens\&. 


.PP
\fBParameters:\fP
.RS 4
\fIfirst\fP token of the list (used as start point for parsing)\&. 
.br
\fIlast\fP token of the list\&. 
.br
\fInext\fP pointer to the next token in the list\&. 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "struct \fBtoken\fP* first"

.SS "struct \fBtoken\fP* last"

.SS "struct \fBtoken\fP* next"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
