.TH "var_storage" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
var_storage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <var_storage\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBvariable\fP ** \fBvariables\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBvariable\fP** variables"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
