.TH "src/storage/var_storage.h" 3 "Mon May 25 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/storage/var_storage.h \- Var storage structures and functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include '\&.\&./utils/xalloc\&.h'\fP
.br
\fC#include '\&.\&./utils/string_utils\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBvariable\fP"
.br
.ti -1c
.RI "struct \fBvar_storage\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTORAGE_SIZE\fP   2048"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBvar_type\fP { \fBVAR_INT\fP, \fBVAR_FLOAT\fP, \fBVAR_STRING\fP, \fBVAR_ERROR\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBvar_storage\fP * \fBnew_var_storage\fP (void)"
.br
.ti -1c
.RI "void \fBfree_var_storage\fP (struct \fBvar_storage\fP *storage)"
.br
.ti -1c
.RI "bool \fBvar_exists\fP (struct \fBvar_storage\fP *storage, char *key)"
.br
.ti -1c
.RI "enum \fBvar_type\fP \fBget_var_type\fP (char *value)"
.br
.ti -1c
.RI "bool \fBput_var\fP (struct \fBvar_storage\fP *storage, char *key, char *val)"
.br
.ti -1c
.RI "bool \fBdel_var\fP (struct \fBvar_storage\fP *storage, char *key)"
.br
.ti -1c
.RI "struct \fBvariable\fP * \fBget_var\fP (struct \fBvar_storage\fP *storage, char *key)"
.br
.ti -1c
.RI "char * \fBget_value\fP (struct \fBvar_storage\fP *storage, char *key)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBvar_storage\fP * \fBalias_storage\fP"
.br
.ti -1c
.RI "struct \fBvar_storage\fP * \fBvar_storage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Var storage structures and functions\&. 


.PP
\fBAuthor:\fP
.RS 4
Team 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2020-05-03
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define STORAGE_SIZE   2048"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBvar_type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIVAR_INT \fP\fP
.TP
\fB\fIVAR_FLOAT \fP\fP
.TP
\fB\fIVAR_STRING \fP\fP
.TP
\fB\fIVAR_ERROR \fP\fP
.SH "Function Documentation"
.PP 
.SS "bool del_var (struct \fBvar_storage\fP * storage, char * key)"

.SS "void free_var_storage (struct \fBvar_storage\fP * storage)"

.SS "char* get_value (struct \fBvar_storage\fP * storage, char * key)"

.SS "struct \fBvariable\fP* get_var (struct \fBvar_storage\fP * storage, char * key)"

.SS "enum \fBvar_type\fP get_var_type (char * value)"

.SS "struct \fBvar_storage\fP* new_var_storage (void)"

.SS "bool put_var (struct \fBvar_storage\fP * storage, char * key, char * val)"

.SS "bool var_exists (struct \fBvar_storage\fP * storage, char * key)"

.SH "Variable Documentation"
.PP 
.SS "struct \fBvar_storage\fP* alias_storage"

.SS "struct \fBvar_storage\fP* \fBvar_storage\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
