.TH "variable" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
variable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <var_storage\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBkey\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.ti -1c
.RI "enum \fBvar_type\fP \fBtype\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* key"

.SS "enum \fBvar_type\fP type"

.SS "char* value"


.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
