.TH "src/utils/xalloc.c" 3 "Sat May 30 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/xalloc.c
.SH SYNOPSIS
.br
.PP
\fC#include <err\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include '\&.\&./utils/xalloc\&.h'\fP
.br
\fC#include '\&.\&./garbage_collector/garbage_collector\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBxmalloc\fP (size_t size)"
.br
.RI "Safe malloc wrapper\&. "
.ti -1c
.RI "void * \fBxrealloc\fP (void *ptr, size_t size)"
.br
.RI "Safe realloc wrapper\&. "
.ti -1c
.RI "void * \fBxcalloc\fP (size_t nmb, size_t size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* xcalloc (size_t nmb, size_t size)"

.SS "void* xmalloc (size_t size)"

.PP
Safe malloc wrapper\&. 
.PP
\fBParameters\fP
.RS 4
\fIsize\fP the size to allocate 
.RE
.PP
\fBReturns\fP
.RS 4
a pointer to the allocated memory 
.RE
.PP

.SS "void* xrealloc (void * ptr, size_t size)"

.PP
Safe realloc wrapper\&. 
.PP
\fBParameters\fP
.RS 4
\fIptr\fP the pointer to reallocate 
.br
\fIsize\fP the new size to allocate 
.RE
.PP
\fBReturns\fP
.RS 4
a pointer to the allocated memory 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
