.TH "src/utils/xalloc.h" 3 "Wed May 13 2020" "Version v0.1" "42h" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/xalloc.h \- Special allocation functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./utils/attr\&.h'\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBxmalloc\fP (size_t size) \fB__malloc\fP"
.br
.RI "Safe malloc wrapper\&. "
.ti -1c
.RI "void * \fBxrealloc\fP (void *ptr, size_t size)"
.br
.RI "Safe realloc wrapper\&. "
.ti -1c
.RI "void * \fBxcalloc\fP (size_t nmb, size_t size)"
.br
.ti -1c
.RI "void * \fBymalloc\fP (size_t size) \fB__malloc\fP"
.br
.ti -1c
.RI "void * \fByrealloc\fP (void *ptr, size_t size)"
.br
.ti -1c
.RI "void * \fBycalloc\fP (size_t nmb, size_t size)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Special allocation functions\&. 


.PP
\fBAuthor:\fP
.RS 4
Team 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2020-05-03
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void* xcalloc (size_t nmb, size_t size)"

.SS "void* xmalloc (size_t size)"

.PP
Safe malloc wrapper\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP the size to allocate 
.RE
.PP
\fBReturns:\fP
.RS 4
a pointer to the allocated memory 
.RE
.PP

.SS "void* xrealloc (void * ptr, size_t size)"

.PP
Safe realloc wrapper\&. 
.PP
\fBParameters:\fP
.RS 4
\fIptr\fP the pointer to reallocate 
.br
\fIsize\fP the new size to allocate 
.RE
.PP
\fBReturns:\fP
.RS 4
a pointer to the allocated memory 
.RE
.PP

.SS "void* ycalloc (size_t nmb, size_t size)"

.SS "void* ymalloc (size_t size)"

.SS "void* yrealloc (void * ptr, size_t size)"

.SH "Author"
.PP 
Generated automatically by Doxygen for 42h from the source code\&.
